"""Auto migration

Revision ID: 1582c26cb15f
Revises: d031274ad109
Create Date: 2025-06-29 12:20:15.143238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1582c26cb15f'
down_revision = 'd031274ad109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('dados_anteriores', sa.Text(), nullable=True),
    sa.Column('data_acao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_auditoria')
    # ### end Alembic commands ###
