"""Auto migration

Revision ID: 1f54136a26bb
Revises: fd610ed87423
Create Date: 2025-06-29 01:20:49.490460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f54136a26bb'
down_revision = 'fd610ed87423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
