"""Auto migration

Revision ID: 1fda7d50c9cb
Revises: 536f8e56ecef
Create Date: 2025-06-29 01:05:29.934212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fda7d50c9cb'
down_revision = '536f8e56ecef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
