"""Auto migration

Revision ID: 215e18f955f4
Revises: 1582c26cb15f
Create Date: 2025-06-29 12:20:54.430888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215e18f955f4'
down_revision = '1582c26cb15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
