"""Auto migration

Revision ID: 312d4a5a5e2e
Revises: 1f54136a26bb
Create Date: 2025-06-29 01:20:51.499208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312d4a5a5e2e'
down_revision = '1f54136a26bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
