"""Auto migration

Revision ID: 3d03ce7d9580
Revises: 744e8e20cb19
Create Date: 2025-06-29 12:39:31.525672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d03ce7d9580'
down_revision = '744e8e20cb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
