"""Auto migration

Revision ID: 536f8e56ecef
Revises: a074b3b1f261
Create Date: 2025-06-29 01:05:27.831308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536f8e56ecef'
down_revision = 'a074b3b1f261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_usuario', sa.String(length=10), nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
