"""Auto migration

Revision ID: 5a698da946e8
Revises: a07e72835d0c
Create Date: 2025-06-29 12:56:37.464233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a698da946e8'
down_revision = 'a07e72835d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
