"""Auto migration

Revision ID: 744e8e20cb19
Revises: 2d335951709b
Create Date: 2025-06-29 12:31:00.648721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744e8e20cb19'
down_revision = '2d335951709b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
