"""Auto migration

Revision ID: 76867603dcaf
Revises: 98bb64d3414c
Create Date: 2025-06-29 02:34:12.524027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76867603dcaf'
down_revision = '98bb64d3414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
