"""Auto migration

Revision ID: 87556b3066f7
Revises: 3d03ce7d9580
Create Date: 2025-06-29 12:40:17.789258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87556b3066f7'
down_revision = '3d03ce7d9580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
