"""Auto migration

Revision ID: 9101f782bbcd
Revises: 97b0d3f29c03
Create Date: 2025-06-29 16:18:34.169476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9101f782bbcd'
down_revision = '97b0d3f29c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
