"""Auto migration

Revision ID: 92c9ed8648af
Revises: 74406c555929
Create Date: 2025-06-29 13:06:49.898158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c9ed8648af'
down_revision = '74406c555929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
