"""Auto migration

Revision ID: 97b0d3f29c03
Revises: 92c9ed8648af
Create Date: 2025-06-29 16:18:31.890127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b0d3f29c03'
down_revision = '92c9ed8648af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
