"""Auto migration

Revision ID: 98bb64d3414c
Revises: 312d4a5a5e2e
Create Date: 2025-06-29 01:37:42.554014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb64d3414c'
down_revision = '312d4a5a5e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
