"""Adiciona campo ativo à Sprint

Revision ID: a074b3b1f261
Revises: fdfa73a7bbdb
Create Date: 2025-06-28 15:13:24.280345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a074b3b1f261'
down_revision = 'fdfa73a7bbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
