"""Auto migration

Revision ID: a07e72835d0c
Revises: 87556b3066f7
Create Date: 2025-06-29 12:40:19.813450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07e72835d0c'
down_revision = '87556b3066f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
