"""Auto migration

Revision ID: cad47791c230
Revises: cba0f8ffc02a
Create Date: 2025-06-29 11:26:07.636816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad47791c230'
down_revision = 'cba0f8ffc02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
