"""Auto migration

Revision ID: cba0f8ffc02a
Revises: 76867603dcaf
Create Date: 2025-06-29 02:34:14.762369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba0f8ffc02a'
down_revision = '76867603dcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
