"""Auto migration

Revision ID: fd610ed87423
Revises: a61e9950c098
Create Date: 2025-06-29 01:15:32.747695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd610ed87423'
down_revision = 'a61e9950c098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
