"""Criar tabela Sprint

Revision ID: fdfa73a7bbdb
Revises: 
Create Date: 2025-06-28 02:50:33.722749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfa73a7bbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint')
    # ### end Alembic commands ###
